#!/bin/bash

echo -e "\n$0\n"

cd /

if [ ! -d ./usr/local/u/bin ];
then
   echo "$0: Abort.  " `realpath ./usr/local/u/bin`" does not exist"
   exit 1
else
   chown -R jjchkconn:jjchkconn ./usr/local/u/bin/jjchkconn*
   chmod -R  550 ./usr/local/u/bin/jjchkconn*
fi

#chown jjchkconn:jjchkconn ./home/jjchkconn/.config/systemd/*
chown jjchkconn:jjchkconn ./home/jjchkconn/.config/uSysIntChkd/*
chmod u+w ./home/jjchkconn/.config/uSysIntChkd/

#chmod 444 ./home/jjchkconn/.config/systemd/user/*
#chown jjchkconn:jjchkconn ./home/jjchkconn/.config/systemd/user/*

systemctl daemon-reload

systemctl list-unit-files "jj*" || true
#ssh jjchkconn@localhost systemctl --user list-unit-files "jj*" || true

systemctl enable jjchkconn-uSysIntChkd@jjchkconn.service  || true
systemctl start jjchkconn-uSysIntChkd@jjchkconn.service  || true
#ssh jjchkconn@localhost systemctl --user enable jjchkconn-uSysIntChkd@jjchkconn.service  || true
#ssh jjchkconn@localhost systemctl --user start jjchkconn-uSysIntChkd@jjchkconn.service  || true

systemctl enable jjchkconn-alerts-send@jjchkconn.path || true
systemctl start  jjchkconn-alerts-send@jjchkconn.path || true
#ssh jjchkconn@localhost systemctl --user enable jjchkconn-alerts-send@jjchkconn.path || true
#ssh jjchkconn@localhost systemctl --user start  jjchkconn-alerts-send@jjchkconn.path || true


### DON'T ENABLE OR START THIS SERVICE.  IT WILL BE TRIGGERED 
### ONLY BY ITS CORRESPONDING .PATH UNIT.
#ssh jjchkconn@localhost systemctl --user enable jjchkconn-alerts-send@jjchkconn.service || true
#ssh jjchkconn@localhost systemctl --user start jjchkconn-alerts-send@jjchkconn.service || true

# Append to /etc/aliases
cat << EOF >> /etc/aliases
jjchkconn: /home/jjchkconn/alerts/inbound-alerts
alerts: /home/jjchkconn/alerts/inbound-alerts 
EOF

# Update aliases database
newaliases

systemctl status -a "jj*" || true
#ssh jjchkconn@localhost systemctl --user status "jj*" || true

echo -e "\n\nREMEMBER TO CUSTOMIZE YOUR SLACK WEBHOOKS PARAMETER IN THE .INI FILE."
echo -e "\nIT IS NOT CONFIGURED RIGHT NOW.\n"
echo -e "\n\nALSO, VERIFY THE .NEXT AND .STEPS FILES."
echo -e "\nInstallation is complete.\n"
