#!/bin/bash

echo -e "\n$0\n"

cd /

if [ ! -d ./usr/local/u/bin ];
then
   echo "$0: Abort.  " `realpath ./usr/local/u/bin`" does not exist"
   exit 1
else
   chown -R jjchkconn:jjchkconn ./usr/local/u/bin/jjchkconn*
   chmod -R  550 ./usr/local/u/bin/jjchkconn*
fi

chown jjchkconn:jjchkconn ./home/jjchkconn/.config/systemd/*
chown jjchkconn:jjchkconn ./home/jjchkconn/.config/uSysIntChkd/*
chmod u+w ./home/jjchkconn/.config/uSysIntChkd/

chmod 444 ./home/jjchkconn/.config/systemd/user/*
chown jjchkconn:jjchkconn ./home/jjchkconn/.config/systemd/user/*

ssh jjchkconn@localhost systemctl --user list-unit-files "jj*" || true

ssh jjchkconn@localhost systemctl --user enable jjchkconn-uSysIntChkd@jjchkconn.service  || true
ssh jjchkconn@localhost systemctl --user start jjchkconn-uSysIntChkd@jjchkconn.service  || true

ssh jjchkconn@localhost systemctl --user enable jjchkconn-alerts-send@jjchkconn.path || true
ssh jjchkconn@localhost systemctl --user start  jjchkconn-alerts-send@jjchkconn.path || true

ssh jjchkconn@localhost systemctl --user enable jjchkconn-alerts-send@jjchkconn.service || true
ssh jjchkconn@localhost systemctl --user start jjchkconn-alerts-send@jjchkconn.service || true

# Append to /etc/aliases
cat << EOF >> /etc/aliases
jjchkconn: /home/jjchkconn/alerts/inbound-alerts
alerts: /home/jjchkconn/alerts/inbound-alerts 
EOF

# Update aliases database
newaliases

echo -e "\n\nREMEMBER TO CUSTOMIZE YOUR SLACK WEBHOOKS PARAMETER."
echo -e "\nIT IS NOT CONFIGURED RIGHT NOW.\n"
echo -e "\nInstallation is complete.\n"
