#!/bin/bash

echo -e "\n$0\n"

while true; do
    deluser --remove-home jjchkconn
    exit_code=$?
    if [ $exit_code -eq 2 ] || [ $exit_code -eq 0 ]; then
        break
    else
        sleep 2
    fi
done
delgroup jjchkconn || true

for n in "jjchkconn: \/home\/jjchkconn\/alerts\/inbound-alerts" "alerts: \/home\/jjchkconn\/alerts\/inbound-alerts"; do sed -i "/$n/d" /etc/aliases; done

echo -e "\nPackage jjchkconn REMOVAL IS COMPLETE"
