#!/bin/bash

cd /

echo -e "\n$0\n"

addgroup jjchkconn

adduser --disabled-password --shell /bin/bash --home /home/jjchkconn --ingroup jjchkconn --gecos '' jjchkconn

usermod -aG cdrom,plugdev jjchkconn

id jjchkconn

while [ ! -d ./home/jjchkconn ]
do
  sleep 1
done

whoami
export ROOTPUB=`cat /root/.ssh/*.pub`
su -l jjchkconn -c 'ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519'
while [ ! -d ./home/jjchkconn/.ssh ]
do
  sleep 1
done

su -l jjchkconn -c 'touch ~/.ssh/authorized_keys'
su -l jjchkconn -c 'chmod 600 ~/.ssh/authorized_keys'
su -l jjchkconn -c "echo $ROOTPUB >> ~/.ssh/authorized_keys"

sleep 1

if [ ! -d ./home/jjchkconn/.config ];
then
   mkdir -p     ./home/jjchkconn/.config
   while [ ! -d ./home/jjchkconn/.config ]
   do
     sleep 1
   done
   chmod 700 ./home/jjchkconn/.config
   chown jjchkconn:jjchkconn ./home/jjchkconn/.config
fi

mkdir -p     ./home/jjchkconn/.config/uSysIntChkd
while [ ! -d ./home/jjchkconn/.config/uSysIntChkd ]
do
  sleep 1
done
chmod 750 ./home/jjchkconn/.config/uSysIntChkd
chown jjchkconn:jjchkconn ./home/jjchkconn/.config/uSysIntChkd

mkdir -p     ./home/jjchkconn/alerts
while [ ! -d ./home/jjchkconn/alerts ]
do
  sleep 1
done
chmod 775 ./home/jjchkconn/alerts
chown postfix:mail ./home/jjchkconn/alerts

if [ ! -d ./usr/local/u/bin ];
then
   mkdir -p     ./usr/local/u/bin
   while [ ! -d ./usr/local/u/bin ]
   do
     sleep 1
   done
   chown -R root:root ./usr/local/u
   chmod -R  775 ./usr/local/u
fi

ALERTSINI=./home/jjchkconn/.config/jjchkconn-slack-alerts.ini

if [ ! -s ${ALERTSINI} ];
then
   echo 'WebHook=https://hooks.slack.com/services/' > ${ALERTSINI}
fi
chmod 700 ${ALERTSINI}
