#!/bin/bash

echo -e "\n$0\n"

### TEMPORARILY STOP HERE. NEED TO DEBUG WHY SYSTEMCTL --USER FAILS.

systemctl status -a "jj*" || true
#ssh jjchkconn@localhost systemctl --user status "jj*" || true

#exit 0

systemctl stop jjchkconn-uSysIntChkd@jjchkconn.serviceg || true
systemctl disable jjchkconn-uSysIntChkd@jjchkconn.service || true
#ssh jjchkconn@localhost systemctl --user stop jjchkconn-uSysIntChkd@jjchkconn.serviceg || true
#ssh jjchkconn@localhost systemctl --user disable jjchkconn-uSysIntChkd@jjchkconn.service || true

systemctl stop jjchkconn-alerts-send@jjchkconn.path || true
systemctl disable jjchkconn-alerts-send@jjchkconn.path || true
#ssh jjchkconn@localhost systemctl --user stop jjchkconn-alerts-send@jjchkconn.path || true
#ssh jjchkconn@localhost systemctl --user disable jjchkconn-alerts-send@jjchkconn.path || true

systemctl stop jjchkconn-alerts-send@jjchkconn.service || true
systemctl disable jjchkconn-alerts-send@jjchkconn.service || true
#ssh jjchkconn@localhost systemctl --user stop jjchkconn-alerts-send@jjchkconn.serviceg || true
#ssh jjchkconn@localhost systemctl --user disable jjchkconn-alerts-send@jjchkconn.serviceg || true

sleep 1
