#!/bin/bash

echo -e "\n$0\n"

systemctl status -a "jj*" |cat || true

systemctl stop jjchkconn-uSysIntChkd@jjchkconn.service || true
systemctl disable jjchkconn-uSysIntChkd@jjchkconn.service || true

systemctl stop jjchkconn-alerts-send@jjchkconn.path || true
systemctl disable jjchkconn-alerts-send@jjchkconn.path || true

systemctl stop jjchkconn-alerts-send@jjchkconn.service || true
systemctl disable jjchkconn-alerts-send@jjchkconn.service || true

sleep 1
